import { Controller } from "@hotwired/stimulus"

// "START AT" picker — choose whether a new/imported task enters the pipeline at
// Briefing (the default) or skips straight to Details Gathering.
//
// Two shapes share this controller:
//  - card    : the New idea modal's two big option cards (title + hint), which
//              also relabel the submit button ("Save & start briefing/details").
//  - segment : the Jira picker's compact segmented toggle, which additionally
//              rewrites each ticket's hidden start_stage field so importing a
//              ticket lands on the chosen stage.
//
// The chosen value is mirrored into every `field` target (hidden inputs) so the
// plain form POST carries it — no JS-only state.
export default class extends Controller {
  static targets = ["card", "segment", "field", "submitLabel"]
  static values = { selected: String }

  connect() {
    this.render()
  }

  select(event) {
    event.preventDefault()
    this.selectedValue = event.currentTarget.dataset.stage
    this.render()
  }

  selectedValueChanged() {
    if (this.hasCardTarget || this.hasSegmentTarget) this.render()
  }

  render() {
    const stage = this.selectedValue || "briefing"

    this.cardTargets.forEach((card) => {
      const on = card.dataset.stage === stage
      card.classList.toggle("border-[color:var(--primary)]", on)
      card.classList.toggle("bg-[color:var(--primary-soft)]", on)
      card.classList.toggle("clar-divider", !on)
      const title = card.querySelector("[data-start-stage-title]")
      if (title) {
        title.classList.toggle("clar-text-primary", on)
        title.classList.toggle("clar-text-text", !on)
      }
    })

    this.segmentTargets.forEach((segment) => {
      segment.classList.toggle("clar-seg-item-active", segment.dataset.stage === stage)
    })

    // Explicit targets plus every start_stage hidden input in scope — the Jira
    // browser's per-ticket import forms are generated by button_to, which gives
    // us no place to hang a Stimulus target, so match them by name instead.
    const fields = new Set([
      ...this.fieldTargets,
      ...this.element.querySelectorAll('input[name="start_stage"]'),
    ])
    fields.forEach((field) => {
      field.value = stage
    })

    // Board tabs reload the turbo-frame, which would otherwise re-render this
    // controller at its default — carry the choice in the link so it survives.
    this.element.querySelectorAll("[data-start-stage-link]").forEach((link) => {
      const url = new URL(link.href, window.location.origin)
      url.searchParams.set("start_stage", stage)
      link.href = url.pathname + url.search
    })

    this.submitLabelTargets.forEach((el) => {
      el.textContent = stage === "details" ? "Save & start details" : "Save & start briefing"
    })
  }
}
